#!/bin/bash

echo "==================================Auto Install Script For Manjarro: ======================================================"

echo "==================================INSTALLING: Google Chrome======================================================"
sudo pacman -S --needed base-devel git
git clone https://aur.archlinux.org/yay-git.git
cd yay-git
makepkg -si
yay -S google-chrome 0y
yay -Syu -y
cd ../
rm -rf yay-git
echo "==============================================================================================================="


echo "==================================INSTALLING: Sublime Text====================================================="
git clone https://aur.archlinux.org/snapd.git
cd snapd
makepkg -si
sudo systemctl enable --now snapd.socket
sudo ln -s /var/lib/snapd/snap /snap
sudo snap install sublime-text --classic
cd ../
rm -rf snapd
echo "==============================================================================================================="

sudo snap install vim-editor --beta
sudo pacman -S vim
sudo pacman -S terminator
sudo pacman -S gpart
sudo pacman -S meld
sudo pacman -S aircrack-ng
sudo pacman -S wireshark-qt
sudo pacman -S ripgrep
sudo pacman -S lazygit
sudo pacman -S tree
sudo pacman -S k
yay -S discord

sudo pacman -Syu

