#!/bin/bash

echo "==================================Auto Install Script For Ubuntu: ======================================================"
sudo apt-get update -y
sleep 2
sudo apt-get upgrade -y
sleep 2

echo "==================================INSTALLING: Google Chrome======================================================"


sudo apt install wget
wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
sudo dpkg -i google-chrome-stable_current_amd64.deb
sudo apt-get install -f


echo "==============================================================================================================="

echo "==================================INSTALLING: Sublime Text====================================================="
wget -qO - https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
echo "deb https://download.sublimetext.com/ apt/stable/" | sudo tee /etc/apt/sources.list.d/sublime-text.list
sudo apt-get update -y
sudo apt-get install sublime-text -y
echo "==============================================================================================================="

echo "==================================INSTALLING: ATOM====================================================="
sudo apt update -y
sudo apt install software-properties-common apt-transport-https wget
wget -q https://packagecloud.io/AtomEditor/atom/gpgkey -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main"
sudo apt install atom -y
sleep 2
echo "==============================================================================================================="



echo "==================================INSTALLING: VSCODE====================================================="
sudo apt-get install wget gpg
wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > packages.microsoft.gpg
sudo install -D -o root -g root -m 644 packages.microsoft.gpg /etc/apt/keyrings/packages.microsoft.gpg
sudo sh -c 'echo "deb [arch=amd64,arm64,armhf signed-by=/etc/apt/keyrings/packages.microsoft.gpg] https://packages.microsoft.com/repos/code stable main" > /etc/apt/sources.list.d/vscode.list'
rm -f packages.microsoft.gpg
sudo apt install apt-transport-https
sudo apt update
sudo apt install code
echo "===============================================================================================================" 

sudo apt-get install vim -y
sleep 2
sudo apt-get install net-tools -y
sleep 2
sudo apt-get install terminator -y
sleep 2
sudo apt-get install vlc -y
sleep 2
sudo apt-get install gpart -y
sleep 2
sudo apt-get install meld  -y
sleep 2
sudo apt-get install aircrack-ng -y
sleep 2
sudo apt-get install wireshark -y
sleep 2
sudo apt-get update -y
sleep 2

echo "==================================ENDING INSTALATION ---> REBOOTING======================================================"
sudo apt-get update -y
sleep 2
sudo apt-get upgrade -y
sleep 2
echo "==============================================================================================================="


cat >> ~/.bashrc << EOF
alias cb="vim ~/.bashrc"
alias sb="source ~/.bashrc"
alias sl="ls"
alias rf="rm -rf "
alias zp="zip"
alias c="clear"
alias r="reset"
alias uz="unzip"
alias tb="tail ~/.bashrc -n "
alias open="xdg-open"
alias uztar=="tar -xvf "
alias file="nautilus"
EOF

reboot
