#!/bin/bash

echo "==================================Auto Install Script For Ubuntu: ======================================================"
sudo apt-get update -y
sleep 2
sudo apt-get upgrade -y
sleep 2

echo "==================================INSTALLING: Google Chrome======================================================"
wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
sleep 2
echo 'deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main' | sudo tee /etc/apt/sources.list.d/google-chrome.list
sleep 2
sudo apt-get update -y
sleep 2
sudo apt-get install google-chrome-stable  -y
sleep 2
echo "==============================================================================================================="

echo "==================================INSTALLING: Sublime Text====================================================="
sudo apt update -y
sudo apt install apt-transport-https ca-certificates curl software-properties-common
curl -fsSL https://download.sublimetext.com/sublimehq-pub.gpg | sudo apt-key add -
sudo add-apt-repository "deb https://download.sublimetext.com/ apt/stable/"
sudo apt update -y
sudo apt install sublime-text -y
sleep 2
echo "==============================================================================================================="

echo "==================================INSTALLING: ATOM====================================================="
sudo apt update -y
sudo apt install software-properties-common apt-transport-https wget
wget -q https://packagecloud.io/AtomEditor/atom/gpgkey -O- | sudo apt-key add -
sudo add-apt-repository "deb [arch=amd64] https://packagecloud.io/AtomEditor/atom/any/ any main"
sudo apt install atom
sleep 2
echo "==============================================================================================================="

sudo apt-get install net-tools -y
sleep 2
sudo apt-get install terminator -y
sleep 2
sudo apt-get install vlc -y
sleep 2
sudo apt-get install gpart -y
sleep 2
sudo apt-get install meld  -y
sleep 2
sudo apt-get install aircrack-ng -y
sleep 2
sudo apt-get install wireshark -y
sleep 2
sudo apt-get update -y
sleep 2

echo "==================================ENDING INSTALATION ---> REBOOTING======================================================"
sudo apt-get update -y
sleep 2
sudo apt-get upgrade -y
sleep 2
echo "==============================================================================================================="


cat >> ~/.bashrc << EOF
alias cb="vim ~/.bashrc"
alias sb="source ~/.bashrc"
alias sl="ls"
alias rf="rm -rf "
alias zp="zip"
alias c="clear"
alias r="reset"
alias uz="unzip"
alias tb="tail ~/.bashrc -n "
alias open="xdg-open"
alias uztar=="tar -xvf "
alias file="nautilus"
EOF

reboot
